### ISSUE TITLE
Getting a consensus representation for >2 domains

### ISSUE THREAD

**Issue by joannawolthuis** [NKI-CCB/PRECISE#3]
Hi PRECISE crew! I've read your manuscript and am really interest in using your method on our metabolomics data. However, I'm struggling to figure out how to run your pipeline on more than two groups (where source -> target wouldn't really work anymore). Do you think this is possible, and if so, how should I best approach this? My first thought was to get the first representation from group 1 -> 2, and somehow use that representation and get another consensus, but it feels a bit hacky and I want to make sure I don't invalidate your method.

Kind regards,
Joanna

**Comment by saroudant** [comment]
Hi Joanna,

Thanks for your interest in PRECISE. Happy to help out adapting our tool to your data.
I do not know any obvious way to extend PRECISE to 3+ datasets ; however the one you are suggesting makes a lot of sense. I will contact you by e-mail to discuss it further.

Best regards,
Soufiane
